#!/bin/bash

set -euE


function git() {
    command git -c advice.detachedHead=false "$@"
}

SOURCE_NAME="frr"
SOURCE_REPO="https://github.com/FRRouting/frr"
SOURCE_VERSION="8.2.2"
REPO_REF="frr-8.2.2"
OUTPUT_DIR=${1:-_output}


mkdir -p "${OUTPUT_DIR}"

echo "### cloning ${SOURCE_NAME}"
git clone --quiet --depth 1 --branch "${REPO_REF}" "${SOURCE_REPO}" "${OUTPUT_DIR}/${SOURCE_NAME}"

echo '### Creating orig.tar'
cd "${OUTPUT_DIR}"
rm -rf "${SOURCE_NAME}/.git"
tar -czvf "${SOURCE_NAME}_${SOURCE_VERSION}.orig.tar.gz" "${SOURCE_NAME}"

echo '### building source package'
cd "${SOURCE_NAME}/"
dpkg-buildpackage -us -uc -S -nc -d

